export const data = [
  {
    id: 1,
    name: "Darrel Ellis",
    email: "elementum@nonummyutmolestie.com",
    user: true,
    admin: false,
  },
  {
    id: 2,
    name: "Angela Clemons",
    email: "pharetra.Nam.ac@neque.co.uk",
    user: false,
    admin: false,
  },
  {
    id: 3,
    name: "Amy Steele",
    email: "purus.ac.tellus@dignissimmagna.org",
    user: false,
    admin: false,
  },
  {
    id: 4,
    name: "Beau Solomon",
    email: "Vivamus@auctorMauris.org",
    user: false,
    admin: true,
  },
  {
    id: 5,
    name: "Helen Newton",
    email: "magna.Sed@Seddictum.com",
    user: true,
    admin: true,
  },
  {
    id: 6,
    name: "Marcia Heath",
    email: "in.cursus@facilisisSuspendisse.co.uk",
    user: false,
    admin: false,
  },
  {
    id: 7,
    name: "Isaiah Tran",
    email: "eget.metus@ametconsectetueradipiscing.com",
    user: false,
    admin: true,
  },
  {
    id: 8,
    name: "Brianna Blake",
    email: "Nullam@elitpretium.com",
    user: true,
    admin: true,
  },
  {
    id: 9,
    name: "Hollee Farrell",
    email: "mauris@augue.co.uk",
    user: true,
    admin: false,
  },
  {
    id: 10,
    name: "Gail Frazier",
    email: "Suspendisse@diamlorem.com",
    user: false,
    admin: true,
  },
  {
    id: 11,
    name: "Allistair Ross",
    email: "pede@rutrum.co.uk",
    user: false,
    admin: false,
  },
  {
    id: 12,
    name: "Jonah Franco",
    email: "nisi.sem@etnetuset.edu",
    user: true,
    admin: true,
  },
  {
    id: 13,
    name: "Bertha Fitzgerald",
    email: "ipsum.dolor@Maecenasiaculis.co.uk",
    user: false,
    admin: false,
  },
  {
    id: 14,
    name: "Marshall Bishop",
    email: "ultricies.sem.magna@Nulla.edu",
    user: false,
    admin: false,
  },
  {
    id: 15,
    name: "Quinlan Benson",
    email: "ultrices.a@aliquetProinvelit.com",
    user: false,
    admin: false,
  },
  {
    id: 16,
    name: "Samuel Reyes",
    email: "lorem.fringilla.ornare@nuncQuisqueornare.ca",
    user: true,
    admin: true,
  },
  {
    id: 17,
    name: "Aquila Holder",
    email: "quam.a.felis@intempus.co.uk",
    user: false,
    admin: false,
  },
  {
    id: 18,
    name: "Renee West",
    email: "nunc.sed@nequeseddictum.ca",
    user: true,
    admin: true,
  },
  {
    id: 19,
    name: "Vivian Grant",
    email: "in.lobortis.tellus@faucibus.edu",
    user: true,
    admin: true,
  },
  {
    id: 20,
    name: "Danielle Leonard",
    email: "interdum.ligula@Integeridmagna.co.uk",
    user: true,
    admin: false,
  },
  {
    id: 21,
    name: "John Sandoval",
    email: "velit.Cras@sapien.org",
    user: false,
    admin: false,
  },
  {
    id: 22,
    name: "Rowan French",
    email: "Integer.mollis.Integer@eu.com",
    user: true,
    admin: true,
  },
  {
    id: 23,
    name: "Alisa Moody",
    email: "Nullam@sapien.ca",
    user: false,
    admin: false,
  },
  {
    id: 24,
    name: "Dexter Lester",
    email: "Suspendisse.eleifend@sociisnatoque.edu",
    user: false,
    admin: true,
  },
  {
    id: 25,
    name: "Galvin Davidson",
    email: "magna.et@velnislQuisque.net",
    user: true,
    admin: true,
  },
  {
    id: 26,
    name: "Hamilton Alford",
    email: "nisi.nibh.lacinia@dapibusgravidaAliquam.net",
    user: true,
    admin: false,
  },
  {
    id: 27,
    name: "Michelle Olson",
    email: "mauris.sagittis@eleifendCrassed.co.uk",
    user: false,
    admin: false,
  },
  {
    id: 28,
    name: "Wallace Pratt",
    email: "ipsum.dolor@Crasconvallisconvallis.co.uk",
    user: false,
    admin: false,
  },
  {
    id: 29,
    name: "Kelly Branch",
    email: "Phasellus.dolor@amet.ca",
    user: true,
    admin: true,
  },
  {
    id: 30,
    name: "Phelan Glenn",
    email: "rhoncus@et.org",
    user: false,
    admin: false,
  },
  {
    id: 31,
    name: "Jasper Wilkerson",
    email: "varius.ultrices.mauris@elit.net",
    user: true,
    admin: false,
  },
  {
    id: 32,
    name: "Brenden Simmons",
    email: "nibh.vulputate.mauris@lacus.org",
    user: true,
    admin: true,
  },
  {
    id: 33,
    name: "Brittany Phillips",
    email: "auctor.quis@felis.org",
    user: true,
    admin: true,
  },
  {
    id: 34,
    name: "Emma Hines",
    email: "at@libero.com",
    user: true,
    admin: false,
  },
  {
    id: 35,
    name: "Stone Parrish",
    email: "est@velit.edu",
    user: false,
    admin: false,
  },
  {
    id: 36,
    name: "Justine Hays",
    email: "aliquet.vel@lobortis.com",
    user: false,
    admin: true,
  },
  {
    id: 37,
    name: "Quinn Finch",
    email: "et.malesuada@necmollisvitae.org",
    user: false,
    admin: false,
  },
  {
    id: 38,
    name: "Tanek Mckee",
    email: "ut.ipsum@nec.edu",
    user: false,
    admin: false,
  },
  {
    id: 39,
    name: "Cameron Yang",
    email: "consectetuer@euismodacfermentum.edu",
    user: true,
    admin: true,
  },
  {
    id: 40,
    name: "Kirk Reeves",
    email: "eleifend@pedeac.ca",
    user: true,
    admin: false,
  },
  {
    id: 41,
    name: "Cecilia Bartlett",
    email: "lacinia@cubiliaCurae.ca",
    user: true,
    admin: true,
  },
  {
    id: 42,
    name: "Cameron Keith",
    email: "est@maurisipsum.co.uk",
    user: true,
    admin: false,
  },
  {
    id: 43,
    name: "Nayda Vazquez",
    email: "neque@mauriserat.net",
    user: false,
    admin: true,
  },
  {
    id: 44,
    name: "Zelenia Cobb",
    email: "mollis@necleo.edu",
    user: true,
    admin: true,
  },
  {
    id: 45,
    name: "Miranda Hood",
    email: "lacinia.mattis@quis.com",
    user: false,
    admin: true,
  },
  {
    id: 46,
    name: "Xavier Reynolds",
    email: "odio@lacus.org",
    user: true,
    admin: true,
  },
  {
    id: 47,
    name: "Meghan Lee",
    email: "mattis@duiquis.net",
    user: true,
    admin: true,
  },
  {
    id: 48,
    name: "Mara Hess",
    email: "morbi@velarcu.net",
    user: false,
    admin: true,
  },
  {
    id: 49,
    name: "Kelly Horton",
    email: "nunc@nonluctussit.com",
    user: false,
    admin: true,
  },
  {
    id: 50,
    name: "Portia Adkins",
    email: "purus@molestietellus.net",
    user: false,
    admin: false,
  },
  {
    id: 51,
    name: "Wynne Goodwin",
    email: "odio@nequenonquam.net",
    user: false,
    admin: true,
  },
  {
    id: 52,
    name: "Finn Byers",
    email: "posuere.enim.nisl@ametconsectetuer.org",
    user: true,
    admin: true,
  },
  {
    id: 53,
    name: "Harlan Joyce",
    email: "elementum.at@malesuada.co.uk",
    user: false,
    admin: false,
  },
  {
    id: 54,
    name: "Lacy Snider",
    email: "consectetuer.adipiscing@Aliquamfringillacursus.net",
    user: true,
    admin: true,
  },
  {
    id: 55,
    name: "Ira Fletcher",
    email: "egestas.Sed.pharetra@orci.com",
    user: true,
    admin: false,
  },
  {
    id: 56,
    name: "Bethany Mcbride",
    email: "ac.turpis.egestas@semelit.co.uk",
    user: false,
    admin: true,
  },
  {
    id: 57,
    name: "Angelica Shepherd",
    email: "non.dui@variusNam.net",
    user: true,
    admin: true,
  },
  {
    id: 58,
    name: "Carla Lott",
    email: "convallis.convallis@ac.net",
    user: false,
    admin: false,
  },
  {
    id: 59,
    name: "Cameron Preston",
    email: "id.risus@magnatellusfaucibus.org",
    user: true,
    admin: false,
  },
  {
    id: 60,
    name: "Zena Murray",
    email: "Suspendisse.dui@malesuadamalesuada.ca",
    user: false,
    admin: false,
  },
  {
    id: 61,
    name: "Ignatius Waller",
    email: "arcu.Sed.et@nec.org",
    user: true,
    admin: false,
  },
  {
    id: 62,
    name: "Wylie Charles",
    email: "Nullam.feugiat.placerat@tellusimperdietnon.net",
    user: false,
    admin: true,
  },
  {
    id: 63,
    name: "Jana Baldwin",
    email: "consectetuer.cursus.et@magnaatortor.ca",
    user: true,
    admin: true,
  },
  {
    id: 64,
    name: "Illiana Bates",
    email: "ipsum.Suspendisse.non@commodo.edu",
    user: true,
    admin: false,
  },
  {
    id: 65,
    name: "Maryam Tyson",
    email: "Duis.a@utmi.edu",
    user: true,
    admin: false,
  },
  {
    id: 66,
    name: "Desirae Dickerson",
    email: "pretium.neque.Morbi@Morbi.org",
    user: false,
    admin: true,
  },
  {
    id: 67,
    name: "Tate Nolan",
    email: "quis@turpisIn.net",
    user: true,
    admin: true,
  },
  {
    id: 68,
    name: "Violet Frost",
    email: "sem.ut@eratvolutpat.co.uk",
    user: true,
    admin: true,
  },
  {
    id: 69,
    name: "Otto Mcmahon",
    email: "arcu.vel.quam@nasceturridiculus.edu",
    user: false,
    admin: true,
  },
  {
    id: 70,
    name: "Nola Solomon",
    email: "dolor.quam@ultrices.com",
    user: false,
    admin: true,
  },
  {
    id: 71,
    name: "Lucian Potter",
    email: "sem.Nulla@cursusvestibulum.org",
    user: true,
    admin: true,
  },
  {
    id: 72,
    name: "Roary Lang",
    email: "nec.ante.blandit@convallis.com",
    user: false,
    admin: false,
  },
  {
    id: 73,
    name: "Frances Chang",
    email: "enim@atrisus.net",
    user: false,
    admin: false,
  },
  {
    id: 74,
    name: "Natalie Gomez",
    email: "rutrum.lorem@antedictum.edu",
    user: true,
    admin: false,
  },
  {
    id: 75,
    name: "Leo Lawson",
    email: "montes.nascetur.ridiculus@egestasblandit.ca",
    user: false,
    admin: false,
  },
  {
    id: 76,
    name: "Palmer Kidd",
    email: "Fusce@faucibus.edu",
    user: false,
    admin: false,
  },
  {
    id: 77,
    name: "Gillian Taylor",
    email: "ac.nulla@dolorDonec.org",
    user: false,
    admin: false,
  },
  {
    id: 78,
    name: "Abigail Nash",
    email: "posuere.cubilia@nonenimMauris.org",
    user: false,
    admin: false,
  },
  {
    id: 79,
    name: "Illana Glenn",
    email: "morbi@mattis.org",
    user: true,
    admin: false,
  },
  {
    id: 80,
    name: "Austin Owens",
    email: "egestas.urna.justo@egestas.org",
    user: true,
    admin: true,
  },
  {
    id: 81,
    name: "Bell Phillips",
    email: "eu.odio@non.edu",
    user: false,
    admin: false,
  },
  {
    id: 82,
    name: "Denton Cobb",
    email: "lacus.varius@dignissimlacus.net",
    user: true,
    admin: false,
  },
  {
    id: 83,
    name: "Eugenia Mcintyre",
    email: "placerat.eget@Mauris.org",
    user: true,
    admin: true,
  },
  {
    id: 84,
    name: "Gary Hooper",
    email: "facilisis.magna@SedmolestieSed.com",
    user: false,
    admin: true,
  },
  {
    id: 85,
    name: "Owen Hopkins",
    email: "orci.luctus@velfaucibusid.co.uk",
    user: false,
    admin: true,
  },
  {
    id: 86,
    name: "Clayton Riddle",
    email: "taciti.sociosqu@loremeu.co.uk",
    user: false,
    admin: true,
  },
  {
    id: 87,
    name: "Chantale Doyle",
    email: "diam@acsemut.net",
    user: false,
    admin: true,
  },
  {
    id: 88,
    name: "Roanna Harris",
    email: "diam@eu.ca",
    user: false,
    admin: true,
  },
  {
    id: 89,
    name: "Shellie Browning",
    email: "eu.placerat.eget@mienim.com",
    user: false,
    admin: false,
  },
  {
    id: 90,
    name: "Ronan Whitaker",
    email: "eu.placerat@metusAenean.edu",
    user: false,
    admin: false,
  },
  {
    id: 91,
    name: "Nehru Rush",
    email: "augue@elit.net",
    user: true,
    admin: true,
  },
  {
    id: 92,
    name: "Zahir Ashley",
    email: "consequat.dolor@Phasellusnulla.net",
    user: true,
    admin: false,
  },
  {
    id: 93,
    name: "Katell Sykes",
    email: "orci.consectetuer@Maecenasiaculis.ca",
    user: true,
    admin: false,
  },
  {
    id: 94,
    name: "Tyler May",
    email: "adipiscing.elit@dictum.com",
    user: true,
    admin: true,
  },
  {
    id: 95,
    name: "Jennifer Hobbs",
    email: "mollis.lectus.pede@pharetrafelis.org",
    user: false,
    admin: true,
  },
  {
    id: 96,
    name: "Sloane Newman",
    email: "Proin.non.massa@mauris.com",
    user: false,
    admin: false,
  },
  {
    id: 97,
    name: "Blaze Whitney",
    email: "at.velit.Cras@lacusvarius.com",
    user: false,
    admin: false,
  },
  {
    id: 98,
    name: "Dillon Pacheco",
    email: "Ut.sagittis@adipiscing.com",
    user: true,
    admin: false,
  },
  {
    id: 99,
    name: "Cheyenne Wood",
    email: "fringilla.porttitor@indolorFusce.edu",
    user: true,
    admin: false,
  },
  {
    id: 100,
    name: "Keiko Salazar",
    email: "interdum@loremvitae.edu",
    user: true,
    admin: false,
  },
];
